---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  path: ./apps/podinfo
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
