changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🎉 New Features
      labels:
        - feature
        - enhancement
    - title: 📖 Documentation Changes
      labels:
        - documentation
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: 🛠 Breaking Changes
      labels:
        - breaking
    - title: 😌 Daily Changes
      labels:
        - "*"
