---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-manager
  interval: 1m0s #10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging
  # path: ./apps/staging
  prune: true
  wait: true
  timeout: 5m0s
