---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 1m #5m
  url: https://DrPalmeritta.github.io/palmeritta-helm-charts
