---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
