---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
namespace: jenkins
resources:
  # - ../apps/base/jenkins
  - ../base/jenkins
patches:
  - path: jenkins-values.yaml
    target:
      kind: HelmRelease
