---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base/podinfo
  - ../base/kube-prometheus-stack
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: kube-prometheus-stack-values.yaml
    target:
      kind: HelmRelease
