---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m #5m
  git:
    ref:
      branch: gh-pages
  url: https://github.com/stefanprodan/podinfo.git
